services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  byhaskell\NovaPoshtaBundle\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Migrations,Tests}'

  byhaskell\NovaPoshtaBundle\Client\ApiClient:
    arguments:
      $httpClient: '@http_client'
      $apiKey: '%byhaskell_nova_poshta.api_key%'
      $baseUrl: '%byhaskell_nova_poshta.base_url%'

  byhaskell\NovaPoshtaBundle\Service\AddressService:
    arguments: ['@byhaskell\NovaPoshtaBundle\Client\ApiClient']

  byhaskell\NovaPoshtaBundle\NovaPoshta:
    arguments:
      $address: '@byhaskell\NovaPoshtaBundle\Service\AddressService'
    public: true